### ISSUE TITLE
why does the Kalman filter correct first then predict?

### ISSUE THREAD

**Issue by ultimatedigiman** [SriramEmarose/Motion-Prediction-with-Kalman-Filter#3]
In the standard Kalman filter pipeline, the Kalman filter will **predict** first then **correct** the prediction value.

But in this repo, you did **correct**  first , what's the reason?

https://github.com/SriramEmarose/Motion-Prediction-with-Kalman-Filter/blob/3c1214d03f20ecb36cc5e8d4fda8251fa2e72262/KalmanFilter.py#L21-L26

**Comment by SriramEmarose** [comment]
Thanks for spotting, You are right. Corrected it.
